First pull request
shubhcctech/Console_Application pull request #1
Opened 2024-01-31 05:17 UTC by shubhcctech

2024-01-31 05:31 UTC, ombothe08 requested changes
please do changes

2024-01-31 05:31 UTC, ombothe08 commented on src/Circle.cpp
> +
remove this space

2024-02-05 03:21 UTC, Coderanildangi requested changes

2024-02-05 03:21 UTC, Coderanildangi commented on src/Circle.cpp
> +using namespace std;
Do not use globally declare std namespace.

2024-02-05 03:21 UTC, Coderanildangi commented on src/Elipse.cpp
> +    circumference = 3.14 * (3 * (maxAxis + minAxis) - sqrt((3 * maxAxis + minAxis) * (maxAxis + 3 * minAxis)));
Use comments wherever possible.

2024-02-05 03:21 UTC, Coderanildangi commented on src/Triangle.cpp
> +        this->side1 = side1;
Use naming convention like mSide1 instead of side1...

2024-02-05 06:57 UTC, merged